 - name: Install MYSQL Server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install python mysql dep
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9
  - name: Check DB Connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: db.phonestand.in
      filter: version
    ignore_errors: yes  
    register: mysql_connection_output
  - name: print output
    ansible.builtin.debug:
      msg: "{{mysql_connection_output}}"
  - name: set up root password
    ansible.builtin.command: "mysql_secure_installation --set-root-password {{mysql_root_password}}"
    when: mysql_connection_output.failed is true  #dont give {{ }} in when condition  